### ISSUE TITLE
annotationProcessor declaration error in Android Studio 3

### ISSUE THREAD

**Issue by wlky** [permissions-dispatcher/PermissionsDispatcher#402] opened 2017-10-28 15:39 UTC
## FAQs

 
___

## Overview

When trying to build the project with Android Studio 3.0 and gradle plugin 3.0 the following error prevents the build from completion:

> Error:Execution failed for task ':socourt:javaPreCompileDemoDebug'.
> Annotation processors must be explicitly declared now.  The following dependencies on the compile classpath are found to contain annotation processor.  Please add them to the annotationProcessor configuration.
>     - permissionsdispatcher-processor-3.0.1.jar (com.github.hotchemi.permissionsdispatcher:permissionsdispatcher-processor:3.0.1)
>   Alternatively, set android.defaultConfig.javaCompileOptions.annotationProcessorOptions.includeCompileClasspath = true to continue with previous behavior.  Note that this option is deprecated and will be removed in the future.
>   See https://developer.android.com/r/tools/annotation-processor-error-message.html for more details.

## Possible Solution
If I remove the "-processor" from the annotationProcessor definition in the gradle file it seems to work. Like this:
`annotationProcessor 'com.github.hotchemi:permissionsdispatcher:3.0.1'`
instead of the way it says in the readme:
`annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:3.0.1'`
## Environment

library version: 3.0.1
gradle plugin: 3.0.0
Android Studio: 3.0
Compile SDK: 26
TargetSDK: 26

**Comment by hotchemi** [comment] 2017-11-01 03:44
'com.github.hotchemi:permissionsdispatcher:3.0.1' is not an annotation processor module so you can't generate code I guess. I couldn't reproduce the problem but have you tries set `includeCompileClasspath = true` ?
Also we appreciate if you provide a minimal sample to reproduce the problem.

**Comment by wlky** [comment] 2017-11-01 09:06
have you tested it with the latest Android Studio version?
I'll provide a sample as soon as a I find the time

**Comment by mannodermaus** [comment] 2017-11-03 02:22
Please share the `dependencies` block of the `build.gradle` file which causes the problem to happen. I use PermissionsDispatcher on AS3 every day without any problems, so I'm absolutely certain that the two required artifacts are getting mixed up in your module, which results in accidentally adding the annotation processor to the compilation classpath.

Using a vanilla project, I'm unable to reproduce this issue in both Java and Kotlin environments if I declare the dependencies as specified in the README. I'm using the now-recommended `implementation` configuration here, instead of `compile`, but it works with the old one as well:

```groovy
dependencies {
  implementation "com.github.hotchemi:permissionsdispatcher:3.0.1"
  kapt "com.github.hotchemi:permissionsdispatcher-processor:3.0.1"
}
```

**Comment by hotchemi** [comment] 2017-11-06 23:51
@wlky let me close the issue, if you're still in trouble please reopen~

**Closed by hotchemi** 2017-11-06 23:51 UTC
Labels: inquiry

**Comment by A86S** [comment] 2017-11-13 19:09
I have found the same issue with android studio 3 and I have removed this error with 
```
implementation "com.github.hotchemi:permissionsdispatcher:3.0.1"
annotationProcessor "com.github.hotchemi:permissionsdispatcher-processor:3.0.1"
```

**Comment by d-rahul** [comment] 2018-06-21 06:45
https://readyandroid.wordpress.com/annotation-processors-must-be-explicitly-declared-now-android-build-gradle/
