### ISSUE TITLE
unresolved reference - this 

### ISSUE THREAD

**Issue by gokukish** [permissions-dispatcher/PermissionsDispatcher#522] opened 2018-09-07 11:37 UTC
## Overview

- Describe the issue briefly
   Doesn't compile when adding correctErrorTypes = true in kapt and kotin compiler throwing error as 
  **unresolved reference: 'this'**. But removing the correctErrorTypes = true compiles unsucessful

### Expected
- What is the expected behavior?
  Compile sucessfully

### Actual

- What is the actual behavior?
  not compile sucessfully

## Environment
     kotlin gradle plugin  - 1.2.61
     support lib - 27.1.1

- Which library version are you using?
  3.3.1
![image](https://user-images.githubusercontent.com/22348175/45217074-60111f80-b2c0-11e8-9dc8-45e0b70d965f.png)

**Comment by hotchemi** [comment] 2018-09-11 04:29
@gokukish sorry for the late, I suppose the problem is addressed in https://github.com/permissions-dispatcher/PermissionsDispatcher/pull/504. Do you think is it possible to use 4.x ver? 👀

**Comment by gokukish** [comment] 2018-09-11 05:01
when using  4.x version. I got AAPT2 error
![image](https://user-images.githubusercontent.com/22348175/45338972-bd9db880-b5ad-11e8-801f-2784e50ba82d.png)

**Comment by Moosphan** [comment] 2018-09-11 05:50
@hotchemi @gokukish i faced the same problem when i used kotlin:
```
error: resource android:attr/ttcIndex not found.
Message{kind=ERROR, text=error: resource android:attr/ttcIndex not found., sources=[/Users/moos/.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.0.0.aar/78b0eb2e813e002483114a69d50ce9ff/res/values/values.xml:246:5-69], original message=, tool name=Optional.of(AAPT)}

```

**Comment by gokukish** [comment] 2018-09-11 05:52
@hotchemi can you bump support lib version to >=27.1.1

**Comment by hotchemi** [comment] 2018-09-11 06:12
4.x is based on jetpack so that you can't mix with old support lib(thus alpha yet)
ref: https://github.com/permissions-dispatcher/PermissionsDispatcher/blob/master/CHANGELOG.md#changelog

**Closed** 2018-09-11 17:47 UTC
Labels: inquiry
