### ISSUE TITLE
sample app crashes when returning from setting

### ISSUE THREAD

**Issue by liangruiyuwanba** [permissions-dispatcher/PermissionsDispatcher#356] opened 2017-08-28 09:23 UTC
when current activity jump to system setting page to set some permissions ,user select close one permission and then switch current activity again,the app crashed,but if user don't operation or select open one permission,this case will not happen

**Comment by hotchemi** [comment] 2017-08-28 09:47
@liangruiyuwanba could you give us exact crash log?

**Comment by liangruiyuwanba** [comment] 2017-08-28 10:48
no crash log，only the activity crash and then restart，you can test it byself,i guess because the annotations

**Comment by liangruiyuwanba** [comment] 2017-08-28 10:53
detail log:
08-28 18:52:43.536 22079-22079/? E/SchedPolicy: open of dev/cpuctl/limit_fg/tasks failed: No such file or directory
08-28 18:52:43.536 22079-22079/? E/SchedPolicy: open of dev/cpuctl/bg_non_interactive/limit_bg/tasks failed: No such file or directory
08-28 18:52:43.539 22079-22079/? I/art: Late-enabling -Xcheck:jni
08-28 18:52:43.566 22079-22079/? D/ActivityThread: ActivityThread,attachApplication
08-28 18:52:43.747 22079-22079/permissions.dispatcher.sample W/System: ClassLoader referenced unknown path: /data/app/permissions.dispatcher.sample-2/lib/arm
08-28 18:52:43.767 22079-22079/permissions.dispatcher.sample I/InstantRun: starting instant run server: is main process
08-28 18:52:43.807 22079-22079/permissions.dispatcher.sample I/HwCust: Constructor found for class android.app.HwCustActivityImpl
08-28 18:52:43.807 22079-22079/permissions.dispatcher.sample D/HwCust: Create obj success use class android.app.HwCustActivityImpl
08-28 18:52:43.833 22079-22079/permissions.dispatcher.sample V/HwPolicyFactory: : success to get AllImpl object and return....
08-28 18:52:43.840 22079-22079/permissions.dispatcher.sample V/HwWidgetFactory: : successes to get AllImpl object and return....
08-28 18:52:43.842 22079-22079/permissions.dispatcher.sample V/ActivityThread: ActivityThread,callActivityOnCreate
08-28 18:52:43.865 22079-22079/permissions.dispatcher.sample W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
08-28 18:52:43.912 22079-22079/permissions.dispatcher.sample D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
08-28 18:52:43.913 22079-22079/permissions.dispatcher.sample D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
08-28 18:52:43.913 22079-22079/permissions.dispatcher.sample V/BoostFramework: /system/framework/QPerformance.jar be checked ! 
08-28 18:52:43.916 22079-22079/permissions.dispatcher.sample V/BoostFramework: mAcquireFunc method = public int com.qualcomm.qti.Performance.perfLockAcquire(int,int[])
08-28 18:52:43.916 22079-22079/permissions.dispatcher.sample V/BoostFramework: mReleaseFunc method = public int com.qualcomm.qti.Performance.perfLockRelease()
08-28 18:52:43.916 22079-22079/permissions.dispatcher.sample V/BoostFramework: mAcquireTouchFunc method = public int com.qualcomm.qti.Performance.perfLockAcquireTouch(android.view.MotionEvent,android.util.DisplayMetrics,int,int[])
08-28 18:52:43.916 22079-22079/permissions.dispatcher.sample V/BoostFramework: mIOPStart method = public int com.qualcomm.qti.Performance.perfIOPrefetchStart(int,java.lang.String)
08-28 18:52:43.916 22079-22079/permissions.dispatcher.sample V/BoostFramework: mIOPStop method = public int com.qualcomm.qti.Performance.perfIOPrefetchStop()
08-28 18:52:43.919 22079-22079/permissions.dispatcher.sample V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@513ace4
08-28 18:52:43.920 22079-22079/permissions.dispatcher.sample D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
08-28 18:52:43.920 22079-22079/permissions.dispatcher.sample D/CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
08-28 18:52:43.920 22079-22079/permissions.dispatcher.sample V/BoostFramework: BoostFramework() : mPerf = com.qualcomm.qti.Performance@466454d
08-28 18:52:43.975 22079-22079/permissions.dispatcher.sample D/HwGalleryCacheManagerImpl: mIsEffect:false
08-28 18:52:43.986 22079-22079/permissions.dispatcher.sample D/HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f0800a3, context : permissions.dispatcher.sample.MainActivity@ae0b59e, Nhwext : 0, get Blur : disable with , null
08-28 18:52:43.986 22079-22079/permissions.dispatcher.sample D/HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f0800a3, context : permissions.dispatcher.sample.MainActivity@ae0b59e, Nhwext : 0, get Blur : disable with , null
08-28 18:52:44.007 22079-22079/permissions.dispatcher.sample D/ActivityThread: add activity client record, r= ActivityRecord{82ae8ba token=android.os.BinderProxy@5088220 {permissions.dispatcher.sample/permissions.dispatcher.sample.MainActivity}} token= android.os.BinderProxy@5088220
08-28 18:52:44.010 22079-22079/permissions.dispatcher.sample D/TEST: onresume====
08-28 18:52:44.027 22079-22079/permissions.dispatcher.sample I/HwPointEventFilter: do not support AFT because of no config
08-28 18:52:44.039 22079-22079/permissions.dispatcher.sample I/ActivityManager_activity: Resuming ActivityRecord{82ae8ba token=android.os.BinderProxy@5088220 {permissions.dispatcher.sample/permissions.dispatcher.sample.MainActivity}} with isForward=true,forwardBitChanged=false onlyLocalRequest=false
08-28 18:52:44.089 22079-22119/permissions.dispatcher.sample I/Adreno: QUALCOMM build                   : 28fbe1e, I1c3536cac6
                                                                       Build Date                       : 12/27/16
                                                                       OpenGL ES Shader Compiler Version: XE031.09.00.04
                                                                       Local Branch                     : 
                                                                       Remote Branch                    : 
                                                                       Remote Branch                    : 
                                                                       Reconstruct Branch               : 
08-28 18:52:44.094 22079-22119/permissions.dispatcher.sample I/OpenGLRenderer: Initialized EGL, version 1.4
08-28 18:52:44.094 22079-22119/permissions.dispatcher.sample D/OpenGLRenderer: Swap behavior 1
08-28 18:52:44.124 22079-22079/permissions.dispatcher.sample W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
08-28 18:52:44.187 22079-22079/permissions.dispatcher.sample I/ActivityManager_activity: Reporting idle of ActivityRecord{82ae8ba token=android.os.BinderProxy@5088220 {permissions.dispatcher.sample/permissions.dispatcher.sample.MainActivity}} finished=false

**Comment by liangruiyuwanba** [comment] 2017-08-28 11:09
the same question [](https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/302)

**Comment by liangruiyuwanba** [comment] 2017-08-28 11:10
https://github.com/permissions-dispatcher/PermissionsDispatcher/issues/302 . like the same question

**Comment by hotchemi** [comment] 2017-08-28 16:06
@liangruiyuwanba oh are you pointing out our sample app?

**Comment by liangruiyuwanba** [comment] 2017-08-29 02:49
yes,your sample app have the same problem

**Comment by liangruiyuwanba** [comment] 2017-08-29 02:54
MainActivity->android system task key->app info page ->close one permission -> android system task key ->MainActivity ，then mainactivity crash and restart,execute oncreate and onresume method

**Comment by hotchemi** [comment] 2017-08-29 02:55
thank you. are you interested in trying to fix?

**Comment by liangruiyuwanba** [comment] 2017-08-29 02:56
of course ,i want you give me some suggestions

**Comment by hotchemi** [comment] 2017-08-29 03:22
@liangruiyuwanba actually I haven't investigated...please give it a go if you wanna do that!

**Comment by liangruiyuwanba** [comment] 2017-08-29 04:24
May be the cause of the android system

**Comment by yanchengdeng** [comment] 2017-09-07 06:21
I have this iussa too  especially  on  android  7.0  above!  Has fix it ?

**Comment by isabsent** [comment] 2017-12-06 09:01
If you change dangerous permission and goes back to app, it seems Android kills app process:
[link 1](https://stackoverflow.com/questions/37756455/android-runtime-permissions-app-crashes-when-user-revokes-permission-how-to-h), [link 2](https://stackoverflow.com/questions/32992105/android-6-permissions-crash-when-disable-permission-and-go-back-to-the-app), [link 3](https://stackoverflow.com/questions/42808378/handling-permissions-when-we-disable-revoke-them-from-app-settings)

**Comment by hotchemi** [comment] 2018-07-12 03:20
Since no one has interest for this issue for now and seems the cause is on Android system side so let me close the issue

**Closed by hotchemi** 2018-07-12 03:20 UTC
Labels: bug, contributionwelcome
