### ISSUE TITLE
Application restarted after you grant permissions

### ISSUE THREAD

**Issue by JustTrust** [permissions-dispatcher/PermissionsDispatcher#588] opened 2019-02-05 16:25 UTC
## Overview

Application restarted after you grant permissions. 
Its not a crash app just restarted from main activity.
No any error in logs, just few strings about restarting:

2019-02-06 17:00:47.683 I/ActivityManager: Killing 20733:com.aaa.debug/u0a130 (adj 100): permission grant or revoke changed gids
2019-02-06 17:00:47.684 D/ActivityManager: cleanUpApplicationRecord -- 20733
2019-02-06 17:00:47.684 W/ActivityManager: Force removing ActivityRecord{d13e83b u0 com.aaa.debug/com.aaa.activity.CameraActivity t464}: app died, no saved state

### Expected

app shouldn't restart

### Actual

app restarted

## Environment

library version = '3.1.0'
android 7.1.2

## Reproducible steps
Fragment is open,
you request permissions, grant it and app restarted

**Comment by hotchemi** [comment] 2019-02-05 16:35
@JustTrust 

- Can you reproduce the issue with our sample modules?
- If it's happening only on your app can you provide minimum example that we can reproduce the issue?

We've never seen that so I wonder there're something weird in app code. Thx.

**Comment by hotchemi** [comment] 2019-02-06 09:58
@JustTrust what kind of device are you using for test? Sorry I haven't been able to reproduce yet 🤔 And also can we possibly get the GIF which records how app behaves?

**Comment by JustTrust** [comment] 2019-02-06 10:34
Device is [vepoy](http://www.wepoy.com/product_view_16.html)
![video-to-gif](https://user-images.githubusercontent.com/16021604/52335626-853ec100-2a0b-11e9-953d-f59aaba69f64.gif)

**Comment by hotchemi** [comment] 2019-02-07 16:30
Oh weird..we've been testing with emulators and several physical devices but never seen that state before..🤔My next question is if you don't use the library you can deal with it?

**Comment by JustTrust** [comment] 2019-02-08 11:33
I'll try to check it without library, but it needs more time

**Comment by hotchemi** [comment] 2019-02-12 05:47
Any update? 👀

**Comment by JustTrust** [comment] 2019-02-12 11:50
Yes, I copied generated code from dispatcher class in my fragment and got the same behaviour. Maybe its a device related issue, what do you think?

**Comment by DummyCo** [comment] 2019-02-12 15:09
@JustTrust did you try plain android permissions requests with no libraries? They are pretty simple to implement especially for the test case of permission requesting and result basic handling.
https://developer.android.com/training/permissions/requesting
Feels like this issue will persist there. 
What about other apps requesting runtime permissions by the way?

**Comment by JustTrust** [comment] 2019-02-12 15:38
With location permissions everything is fine. I will try to make a test with pure android permissions request.

**Comment by hotchemi** [comment] 2019-02-12 15:43
I suppose the cause is on devise side..let me close the issue for the time being and reopen if needed.
thank you for your contribution! appreciated.

**Closed by hotchemi** 2019-02-12 15:43 UTC
